### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by jstoos** [learn-co-curriculum/sinatra-yield-readme#18]
There is nothing to submit in this lesson, but it requires a submit to finish.  Just FYI when I simply deleted an empty line it ran, but it is confusing.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials so that it functions as a normal readme and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
